apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: Norris
  annotations:
    trait.camel.apache.org/mount.configs: "secret:norris"
    trait.camel.apache.org/mount.resources: "configmap:norris-transform"
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: chuck-norris-source
    properties:
      period: 12000

  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jslt-action
    properties:
      template: c2s.jslt

  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: slack-sink
    properties:
      token: "{{slack.token}}"
